services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "80:8080"
      - "24454:24454"
    environment:
      INIT_MEMORY: 2G
      MAX_MEMORY: 10G
      JVM_OPTS: -XX:SoftMaxHeapSize=5G
      EULA: "TRUE"
      MODPACK_PLATFORM: MODRINTH
      MODRINTH_MODPACK: /data/wip.mrpack
      # server properties
      MOTD: WIP SMP - Insert funny MOTD here
      DIFFICULTY: hard
      ENABLE_WHITELIST: true
      EXISTING_WHITELIST_FILE: MERGE
      ENFORCE_WHITELIST: true
      ICON: data/server-icon.png
      ENABLE_QUERY: true
      MAX_PLAYERS: 20
      MAX_WORLD_SIZE: 29999984
      ALLOW_NETHER: true
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ENABLE_COMMAND_BLOCK: false
      FORCE_GAMEMODE: true
      GENERATE_STRUCTURES: true
      HARDCORE: false
      SNOOPER_ENABLED: false
      MAX_BUILD_HEIGHT: 256
      MAX_TICK_TIME: 30000
      SPAWN_ANIMALS: true
      SPAWN_MONSTERS: true
      SPAWN_NPCS: true
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 10
      MODE: survival
      PVP: true
      LEVEL_TYPE: normal
      LEVEL: world
      ONLINE_MODE: true
      ALLOW_FLIGHT: true
      SERVER_NAME: WIP SMP
      SERVER_PORT: 25565
      SIMULATION_DISTANCE: 10
      PAUSE_WHEN_EMPTY_SECONDS: -1
    volumes:
      - ./data:/data
