command-label: squaremarker
command-aliases:
- marker
- squaremapmarker
- smarker
layer-name: Marker
icon-url: https://github.com/SentixDev/squaremarker/raw/master/resources/default_icon.png
icon-size: 32
show-controls: true
default-hidden: false
update-rate-milliseconds: 5000
